site_name: aerocore
site_description: Lightweight toolbox for air traffic management research
repo_name: abc8747/aerocore
repo_url: https://github.com/abc8747/aerocore
site_url: https://abc8747.github.io/aerocore/
nav:
  - Home: "index.md"
  - Capabilities: "capabilities.md"
  - Fuel Estimation (Acropole): "acropole.md"
  - API Reference:
      - Acropole: "api/acropole.md"
      - Core: "api/core.md"
      - Types: "api/types.md"
      - Data: "api/data.md"
      - Misc: "api/misc.md"

theme:
  name: material
  features:
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
    - navigation.expand
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
plugins:
  - search
  - social
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          inventories:
            - https://docs.python.org/3/objects.inv
            - https://numpy.org/doc/stable/objects.inv
            - https://pola-rs.github.io/polars/py-polars/html/objects.inv # unstable, see https://github.com/pola-rs/polars/issues/7027
            - https://jax.readthedocs.io/en/latest/objects.inv
            - https://abc8747.github.io/isqx/objects.inv
          options:
            inherited_members: true
            members_order: source
            separate_signature: true
            show_signature_annotations: true
            merge_init_into_class: true
            docstring_section_style: table
            signature_crossrefs: true
            show_if_no_docstring: true
            show_submodules: false
            show_source: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_root_heading: true
            show_root_full_path: false
            show_labels: false
            docstring_style: sphinx
            group_by_category: false
      enable_inventory: true
markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - footnotes
  - md_in_html
  - pymdownx.blocks.admonition
  - pymdownx.blocks.details
  - pymdownx.details
  - pymdownx.tilde
  - pymdownx.highlight:
      pygments_lang_class: true
  - pymdownx.magiclink
  - pymdownx.snippets:
      base_path: ["."]
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - assets/js/katex.js
  - https://cdn.jsdelivr.net/npm/katex@0.17.0/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.17.0/dist/contrib/auto-render.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.17.0/dist/contrib/copy-tex.min.js
extra_css:
  - https://cdn.jsdelivr.net/npm/katex@0.17.0/dist/katex.min.css
# see: https://github.com/zensical/zensical/releases/tag/v0.0.38
validation:
  unresolved_references: false